
Title: Airline Passenger Satisfaction Parameter Tuning
Authors: Maike Hucht, Jule Lang, Micahel Prendota, Deniz Terzioglu
Date: April 19, 2024

# Airline Passenger Satisfaction Parameter Tuning

## Table of Contents
<a id="table-of-contents"></a>
- [1  Data Load](#1)
- [2 Data glimpse and Imputing NA ](#2)
    - [2.1 Data glimpse with skim function](#2.1)
    - [2.2 Imputing NA with Mice package](#2.2)
- [3 EDA in Dataset](#3)
    - [3.1 Numeric variable in Dataset](#3.1)
    - [3.2 Scored variable in Dataset](#3.2)
    - [3.3 Character variable in Dataset](#3.3)
- [4 Data Preprocessing](#4)
    - [4.1 Scale](#4.1)
    - [4.2 Ready for the testset](#4.2)
    - [4.3 Factorization](#4.3)
- [5 Building Ranger for Classification](#5)
    - [5.1 Building Ranger parameter](#5.1)
    - [5.2 Model and Prediction](#5.2)
    - [5.3 Graph and Result](#5.3)
[back to top](#table-of-contents)
<a id="1"></a>
# 1 Data Load
# Data Exploration
library(tidyverse)
library(janitor)
library(DataExplorer)
library(skimr)
library(lubridate)

# Modeling
library(tidymodels)
library(caret)

# Visualization
library(ggrepel)
library(GGally)
library(vip)
library(patchwork)
library(ggplot2)

# Tables
library(gt)
library(ranger)

train <- read.csv("../input/airline-passenger-satisfaction/train.csv",stringsAsFactors = F)
test <- read.csv("../input/airline-passenger-satisfaction/test.csv",stringsAsFactors = F)
options(scipen=999) # erase 'e' in number
options(warn = -1)
[back to top](#table-of-contents)
<a id="2"></a>
#  2 Data glimpse and Imputing NA

<a id="2.1"></a>
## 2.1 Data glimpse with skim function
head(train)
head(test)
skim(train)
skim(test)
<a id="2.2"></a>
## 2.2 Imputing NA with Mice package
# Train data
plot_missing(train,title='NA value in Train dataset')

#Test data
plot_missing(test,title='NA value in Test dataset')
There is missing value in the "Arrival.Delay.in.Minutes" feature, So I decide to impute with 'Mice' package
miceresult <- mice::mice(train,seed=123,m=5)#the m is the number of divide
miceresult
train <- mice::complete(miceresult,1)
plot_missing(train,title='NA in Train dataset After Mice')
There is no missing value in the trainset now.
[back to top](#table-of-contents)
<a id="3"></a>
#  3 EDA in Dataset

<a id="3.1"></a>
## 3.1 Numeric variable in Dataset
There are 4 Numeric feature in this dataset. In this graph, I tried to figure it out 'what **difference of distribution** in this feature when they are divided between satisfied or non satisfied
#age histogram
age1<- ggplot(data = train, aes( x = Age)) + 
  geom_density(fill="lightblue", color="black", alpha=0.8) +
  labs(title = "Distribution of Age", 
       subtitle = "Airline Passenger Satisfaction, Kaggle(2021.08)")

age2 <- train %>%
  mutate(satisfaction = recode(satisfaction, `0` = "neutral or dissatisfied", `1` = "satisfied")) %>%
  ggplot(aes(x = Age, fill = satisfaction)) +
  geom_density(alpha = 0.5) +
  labs(x = NULL) +
  theme_bw() +
  facet_wrap(~satisfaction)

age1/age2

#flight distance histogram
flight1<- ggplot(data = train, aes( x = Flight.Distance)) + 
  geom_density(fill="lightblue", color="black", alpha=0.8) +
  labs(title = "Distribution of Flight.Distance", 
       subtitle = "Airline Passenger Satisfaction, Kaggle(2021.08)")

flight2 <- train %>%
  mutate(satisfaction = recode(satisfaction, `0` = "neutral or dissatisfied", `1` = "satisfied")) %>%
  ggplot(aes(x = Flight.Distance, fill = satisfaction)) +
  geom_density(alpha = 0.5) +
  labs(x = NULL) +
  theme_bw() +
  facet_wrap(~satisfaction)

flight1/flight2
#Arrival.Delay.in.Minutes
arrive1<- ggplot(data = train, aes( x = Arrival.Delay.in.Minutes)) + 
  geom_density(fill="lightblue") +
  xlim(0, 75) +
  labs(title = "Distribution of Arrival.Delay.in.Minutes", 
       subtitle = "Airline Passenger Satisfaction, Kaggle(2021.08)")

arrive2 <- train %>%
  mutate(satisfaction = recode(satisfaction, `0` = "neutral or dissatisfied", `1` = "satisfied")) %>%
  ggplot(aes(x = Arrival.Delay.in.Minutes, fill = satisfaction)) +
  geom_density(alpha = 0.5) +
  xlim(0, 75) +
  labs(x = NULL) +
  theme_bw() +
  facet_wrap(~satisfaction)

arrive1/arrive2

#Departure.Delay.in.Minutes
depart1<- ggplot(data = train, aes( x = Departure.Delay.in.Minutes)) + 
  geom_density(fill="lightblue") +
  xlim(0, 75) +
  labs(title = "Distribution of Departure.Delay.in.Minutes", 
       subtitle = "Airline Passenger Satisfaction, Kaggle(2021.08)")

depart2 <- train %>%
  mutate(satisfaction = recode(satisfaction, `0` = "neutral or dissatisfied", `1` = "satisfied")) %>%
  ggplot(aes(x = Departure.Delay.in.Minutes, fill = satisfaction)) +
  geom_density(alpha = 0.5) +
  xlim(0, 75) +
  labs(x = NULL) +
  theme_bw() +
  facet_wrap(~satisfaction)

depart1/depart2
*The interesting thing in the Distribution of 4 numeric feature* is that **last 2 variables** have great skewness to the left. So We need to find the method to reduce this skewness 
<a id="3.2"></a>
## 3.2 Scored variable in Dataset
train %>% 
  select(,9:16) %>% 
  plot_histogram(theme_config = theme_bw(), 
                 geom_histogram_args = list(fill = "salmon"),title = "Scored Variables distirbution in trianset(1)")

train %>% 
  select(,17:22) %>% 
  plot_histogram(theme_config = theme_bw(), 
                 geom_histogram_args = list(fill = "lightblue"),title = "Scored Variables distirbution in trianset(2)")
train %>% 
   select(-c(Gender, Customer.Type, Type.of.Travel, Class,Age,X,id,Flight.Distance,Arrival.Delay.in.Minutes,Departure.Delay.in.Minutes)) %>%
         mutate_at(vars(),funs(as.factor))  %>%
         mutate(satisfaction = recode(satisfaction, `0` = "neutral or dissatisfied", `1` = "satisfied")) %>%
         gather(key, value, Inflight.wifi.service:Cleanliness) %>% 
         group_by(satisfaction, key, value) %>%
         summarize(N = n()) %>%
         ggplot(aes(x = value, y = N, fill = satisfaction)) +
         geom_bar(stat = "identity", position = "fill", colour = "black", alpha = 0.75) +
         theme_bw() +
         facet_wrap(~key, scales = "free")
This is distribution of scored Variables which **are calculated by number**. Some charts have **significant difference between satisfied or non-satisfied** while others don't
<a id="3.3"></a>
## 3.3 Character variable in Dataset
c5 <- train %>% 
  mutate(satisfaction = recode(satisfaction, `0` = "neutral or dissatisfied", `1` = "satisfied")) %>%
  count(satisfaction) %>% 
  ggplot(aes(x = satisfaction, y = n, fill = satisfaction)) +
  geom_bar(stat = "identity", colour = "black", alpha = 0.75) +
  geom_text(aes(label = n), position=position_dodge(width=0.9), vjust=-0.5) +
  ylim(0, 60000) +
  labs(y = "Count") +
  theme_bw()  + ggtitle("Sactisfaction variable in Train Dataset")

c1 <-train %>% 
  mutate(Gender = recode(Gender, `0` = "Female", `1` = "Male")) %>%
  count(Gender) %>% 
  ggplot(aes(x = Gender, y = n, fill = Gender)) +
  geom_bar(stat = "identity", colour = "black", alpha = 0.75) +
  geom_text(aes(label = n), position=position_dodge(width=0.9), vjust=-0.5) +
  ylim(0, 60000) +
  labs(y = "Count") +
  theme_bw()  + ggtitle("Gender variable in Train Dataset")

c2 <- train %>% 
  mutate(Customer.Type = recode(Customer.Type, `0` = "disloyal Customer", `1` = "Loyal Customer")) %>%
  count(Customer.Type) %>% 
  ggplot(aes(x = Customer.Type, y = n, fill = Customer.Type)) +
  geom_bar(stat = "identity", colour = "black", alpha = 0.75) +
  geom_text(aes(label = n), position=position_dodge(width=0.9), vjust=-0.5) +
  ylim(0, 100000) +
  labs(y = "Count") +
  theme_bw() + ggtitle("Customer.Type variable in Train Dataset")

c3 <- train %>% 
  mutate(Type.of.Travel = recode(Type.of.Travel, `0` = "Business travel", `1` = "Personal Travel")) %>%
  count(Type.of.Travel) %>% 
  ggplot(aes(x = Type.of.Travel, y = n, fill = Type.of.Travel)) +
  geom_bar(stat = "identity", colour = "black", alpha = 0.75) +
  geom_text(aes(label = n), position=position_dodge(width=0.9), vjust=-0.5) +
  ylim(0, 100000) +
  labs(y = "Count") +
  theme_bw()  + ggtitle("Type.of.Travel variable in Train Dataset")

c4 <- train %>% 
  mutate(Class = recode(Class, `0` = "Business", `1` = "Eco",`2` = "Eco Plus")) %>%
  count(Class) %>% 
  ggplot(aes(x = Class, y = n, fill = Class)) +
  geom_bar(stat = "identity", colour = "black", alpha = 0.75) +
  geom_text(aes(label = n), position=position_dodge(width=0.9), vjust=-0.5) +
  ylim(0, 100000) +
  labs(y = "Count") +
  theme_bw() + ggtitle("Class variable in Train Dataset")

c1/c2
c3/c4
c5
train %>% 
   select(Gender, Customer.Type, Type.of.Travel, Class,satisfaction) %>% 
         mutate_at(vars(Gender, Customer.Type, Type.of.Travel, Class,satisfaction),funs(as.factor)) %>%
         mutate(satisfaction = recode(satisfaction, `0` = "neutral or dissatisfied", `1` = "satisfied")) %>%
         gather(key, value, Class:Gender) %>% 
         group_by(satisfaction, key, value) %>%
         summarize(N = n()) %>%
         ggplot(aes(x = value, y = N, fill = satisfaction)) +
         geom_bar(stat = "identity", position = "fill", colour = "black", alpha = 0.75) +
         theme_bw() +
         facet_wrap(~key, scales = "free")
This is the Distribution of **Categorial Varibales**. 
[back to top](#table-of-contents)
<a id="4"></a>
#  4 Data Preprocessing

<a id="4.1"></a>
## 4.1 Scale
**Standardization** It is a step of Data Pre Processing which is applied to independent variables or features of data. It basically helps to normalise the data within a particular range. Sometimes, it also helps in speeding up the calculations in an algorithm.
train <- train[,-c(1,2)] #delete X, id feature
train[,-c(1,2,4,5,23)] <- scale(train[,-c(1,2,4,5,23)]) #'Gender','Customer.Type','Type.of.Travel','Class','satisfaction'
head(train)
<a id="4.2"></a>
## 4.2 Ready for the testset
#Imputing NA value
miceresult <- mice::mice(test,seed=123,m=5)#the m is the number of divide
miceresult
test <- mice::complete(miceresult,1)

#Scale
test <- test[,-c(1,2)] #delete X, id feature
test[,-c(1,2,4,5,23)] <- scale(test[,-c(1,2,4,5,23)]) #'Gender','Customer.Type','Type.of.Travel','Class','satisfaction'
head(test)
<a id="4.3"></a>
## 4.3 Factorization
train$Gender <- factor(train$Gender)
train$Customer.Type <- factor(train$Customer.Type)
train$Type.of.Travel <- factor(train$Type.of.Travel)
train$Class <- factor(train$Class)
train$satisfaction <- factor(train$satisfaction)

test$Gender <- factor(test$Gender)
test$Customer.Type <- factor(test$Customer.Type)
test$Type.of.Travel <- factor(test$Type.of.Travel)
test$Class <- factor(test$Class)
test$satisfaction <- factor(test$satisfaction)
[back to top](#table-of-contents)
<a id="5"></a>
#  5 Building Ranger for Classification

<a id="5.1"></a>
## 5.1 Building Ranger parameter
# set x and y 
x <- train[,-23]
y <- train$satisfaction

# use caret for grid search 
fit_control <- caret::trainControl(
  method = "cv", 
  number = 3, 
  search = "random",
  classProbs = TRUE
)

# set grid options
grid <- expand.grid(
  mtry = c(2, 4, 6),
  splitrule = c("gini", "extratrees"),
  min.node.size = c(1, 5, 10)
)

# train ranger
model <- train(
  x = x, 
  y = as.factor(make.names(y)),
  method = "ranger",
  trControl = fit_control,
  tuneGrid = grid
)
<a id="5.2"></a>
## 5.2 Model and Prediction
print(model)
importance <- varImp(model, scale = FALSE)
prediction <- predict(model, test[,-23]) %>% as.data.frame() %>% rename('predict'='.')
prediction$predict <- gsub("neutral.or.dissatisfied", "neutral or dissatisfied",prediction$predict)
prediction$predict <- factor(prediction$predict)

answer <- test[,23] %>% as.data.frame() %>% rename('answer'='.')
answer$answer <- factor(answer$answer)
print(importance)
plot(importance)
The most important feature are **"Inflight.wifi.service", "Type.of.Travel", "Online.boarding"**
<a id="5.3"></a>
## 5.3 Graph and Result
ranger_confm <- confusionMatrix(prediction$predict, answer$answer,positive = 'satisfied')
ranger_confm
Here is the Confusion Matrix of Ranger model which can view the **'Accuracy','Sensitivity','Specificity'**
plot_ranger <- as.data.frame(ranger_confm$table)
plot_ranger$Prediction <- factor(plot_ranger$Prediction, levels=rev(levels(plot_ranger$Prediction)))


ggplot(plot_ranger, aes(Prediction,Reference, fill= Freq)) +
  geom_tile() + geom_text(aes(label=Freq)) + theme(legend.position = "None") + scale_fill_gradient(low="#D6EAF8",high = "#2E86C1") +
  ggtitle("Ranger Accuracy:  XX%, Sensitivity: XX%, Specificity: XX%")
So, **The model 'Ranger' have XX% Accuracy, XX% Sensitivity, XX% Specificity**.
The sad thing is that I've tried  a lot of models, but, **It has too many times to load**, thus, I have to choose 'Ranger' with good accuracy and bolt speed.
**If you have a time to upload different model, I'm so glad to see it. Thanks for reading my notebook**😉
